apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: r119td15e-java-springboot
  janus-idp.io/tekton: r119td15e-java-springboot
  backstage.io/kubernetes-id: r119td15e-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: r119td15e-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
